[metadata]
name = qoala-bench
author = QuTech
author_email = s.b.bernheim@tudelft.nl
description = Benchmark tool for qoala programs
long_description = file: README.md
long_description_content_type = text/markdown
license = MIT
url = https://github.com/SoftwareQuTech/qoala-bench
project_urls =
    Source = https://github.com/SoftwareQuTech/qoala-bench
    Paper = https://ieeexplore.ieee.org/document/11662182
    Dataset = https://doi.org/10.4121/bcac962c-fa21-40c5-9908-44ea5ccaaa5a.v1
    euqalyptus = https://softwarequtech.github.io/euqalyptus/
    qoala-mlir = https://softwarequtech.github.io/qoala-mlir/
python_requires = >=3.10.16, <3.13

[options]
packages = qoala_bench
include_package_data = True
install_requires = 
    qoala >=2.1.0
    euqalyptus >=0.1.0
    numpy >=1.26, <2.0
    pydantic >=1.8.2
    pydynaa >=0.3, <2.0
    scipy>=1.4.1,<2.0.0
    netsquid >=1.0.6, <2.0
    netsquid-magic >=14.0, <15.0.0
    netqasm >=2.0, <3.0
    networkx ==3.1
    matplotlib ==3.6.3
    tqdm >=4.0
    mypy >=1.0

[options.extras_require]
dev =
    pytest >=7.1, <8.0
    pytest-xdist >= 3.1, < 4.0
    coverage >= 7.1
    types-PyYAML >=6.0, <7.0
    flake8 >=4.0, <5.0
    isort >=5.10, <5.11
    black >=22.3, <22.4
    mypy >=1.11.2, <1.12
    dacite >= 1.8.1
    build >=1.0
